name: Visual Regression Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  visual-regression-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          # Only install what we need to run the client in-action and tests against it
          # format:    `--filter <packagename>...`
          run_install: |
            - args: [--filter myclient... --filter cypress-tests...]

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm dev
          wait-on: 'http://localhost:3000/'
          command-prefix: 'percy exec -- pnpm exec'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
