name: Visual Regression Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  visual-regression-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: pnpm dev
          wait-on: 'http://localhost:3000/'
          command-prefix: 'percy exec -- pnpm exec'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
